### ISSUE TITLE
Possible typo in Equation (4.35)

### ISSUE THREAD

**Issue by jpmikhail** [Allen-Tildesley/corrections#3]
Hello,

In Equation (4.35) on page 162, I believe the sixth-power component of the potential should have a negative sign before and after the "and."

**Comment by Michael-P-Allen** [comment]
Thanks for pointing this out. I think that you are correct. In the first edition of our book, in the equivalent of eqn (4.34), we defined the V6 term with the negative sign included, and wrote V=V12+V6; in the current edition we define it with V=V12-V6. We could, equivalently, correct eqn (4.35) as you suggest, but I prefer to restore eqn (4.34) to its original form.
