### ISSUE TITLE
Equations 3.49

### ISSUE THREAD

**Issue by alexfleury** [Allen-Tildesley/corrections#4]
Hi,

When trying to derive equations **3.49a** and **3.49b** (p.116), I think I have found 2 typos in them. In fact, they are different from equations 3.59 (p.94) of the first edition.

In short:
(3.49a) m_2^(-2) -> m_2^(-1)
(3.49b) m_3^(-2) -> m_3^(-1)

Thank you very much!

**Comment by Michael-P-Allen** [comment]
Many thanks for pointing this out. It looks as if you are right and, unfortunately, the typos are repeated in eqn (3.53). I'll double check, but the most likely next step is that I'll revise the corrections list and close this issue. Thanks once again.

**Comment by Michael-P-Allen** [comment]
This may not happen immediately, because I want to take a closer look at eqn (3.53), which suddenly looks wrong (the time t at which the bond vectors are evaluated). If there is another error there, I should correct that at the same time.

**Comment by Michael-P-Allen** [comment]
As I suspected, this turned up the same typo in eqns (3.53ab), and also an error in the times at which the bond vectors on the right of eqns (3.53ab) are evaluated. I have updated the erratum list. Thanks once more for raising this issue!
