### ISSUE TITLE
Typo in Appendix E

### ISSUE THREAD

**Issue by jpmikhail** [Allen-Tildesley/corrections#7]
Hello,

I believe there is a small typo on page 510 (section E.2). The sentence beginning "Note that this excludes the possibility . . . " should reference the values of ξ_i, not X_i.

**Comment by Michael-P-Allen** [comment]
Thank you for pointing this out. You are right, of course. I shall add this to the errata document in the next day or so, and at that point will close this issue. Thanks again for your interest in our book.
