### ISSUE TITLE
Potential of dipole molecules

### ISSUE THREAD

**Issue by computbiolgeek** [Allen-Tildesley/corrections#8]
Dear Dr. Allen and Tildesley, it looks like there is a typo on p. 36 line 7. As far as I know v(r) ~ r^(-3) for dipole-dipole interactions. This has not been mentioned in the latest errata. --Bian

**Comment by Michael-P-Allen** [comment]
Dear Bian. Thank you for bringing this to our attention. You are right, the missing negative sign seems to have slipped through. I will update the errata today, and at that point will close this issue. Thanks also for your interest in our book.
